name: Commit Message Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  commit-message-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Tüm commit geçmişini indir

    - name: Get commit messages from the pull request
      run: |
        # Get branch name from the pull request
        BRANCH_NAME=$(echo "${{ github.head_ref }}" | sed 's#/#_#g')
        EXPECTED_PREFIX="[$BRANCH_NAME]"

        # Get commit messages using GitHub API
        COMMITS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits" \
          | jq -r '.[].commit.message')

        # Check if each commit message starts with the expected prefix
        for COMMIT_MSG in $COMMITS; do
          if [[ ! "$COMMIT_MSG" =~ ^\[$BRANCH_NAME\] ]]; then
            echo "Hata: Commit mesajı '$COMMIT_MSG' beklenen formatta değil! (Beklenen prefix: '$EXPECTED_PREFIX')"
            exit 1
          fi
        done

    - name: Success message
      if: success()
      run: echo "Tüm commit mesajları doğru formatta."
