name: Commit Message Checker

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-commit-messages:
    runs-on: ubuntu-latest

    steps:
      - name: Kod Deposu'nu Çek
        uses: actions/checkout@v3

      - name: Commit Mesajlarını Al
        id: commits
        run: |
          # PR'ın temel dalından (base branch) itibaren commitleri al
          COMMITS=$(git log origin/${{ github.event.pull_request.base.ref }}..HEAD --pretty=format:"%s")
          echo "::set-output name=commits::$COMMITS"

      - name: Commit Mesajlarını Kontrol Et
        run: |
          IFS=$'\n' read -rd '' -a commit_array <<< "${{ steps.commits.outputs.commits }}"
          for commit in "${commit_array[@]}"
          do
            # Commit mesajının [yazı] ile başlayıp başlamadığını kontrol et
            if [[ ! "$commit" =~ ^\[[^\]]+\] ]]; then
              echo "Hata: Commit mesajı [yazı] ile başlamalı. Problemli commit: '$commit'"
              exit 1
            fi
          done
          echo "Tüm commit mesajları doğru formatta."
